### ISSUE TITLE
Add the latest build .war file with mysql upgrade

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/sqlinjectionsample#4]
Current .war file available does not contain the latest fixes done to upgrade the mysql JDBC connector. Need to replace it with new one.

**Comment by haridevelops** [comment]
want to build to the war and commit back ?

**Comment by thariyarox** [comment]
Closed the issue as the fix is now available with PR https://github.com/thariyarox/sqlinjectionsample/pull/5
